import { FoodCategory, FoodItem, OutletInfo, Coupon, CustomerProfile } from '@/types/customer';

export const INITIAL_CUSTOMER_PROFILE: CustomerProfile = {
  id: 'cust-101',
  name: 'Surya',
  email: 'surya.customer@restomaster.com',
  phone: '+91 98765 43210',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
  addresses: [
    {
      id: 'addr-1',
      label: 'Home',
      street: '42, Garden View Enclave, Gandhi Nagar',
      apartment: 'Flat 4B, Tower Orchid',
      landmark: 'Near Central Park',
      city: 'Chennai',
      pincode: '600020',
      isDefault: true,
    },
    {
      id: 'addr-2',
      label: 'Work',
      street: '7th Floor, Cyber Wave Tech Hub, OMR Expressway',
      apartment: 'Office Suite 702',
      landmark: 'Opposite Gateway Hotel',
      city: 'Chennai',
      pincode: '600096',
      isDefault: false,
    },
  ],
  preferredOutletId: 'out-001',
  preferredOrderType: 'DINE_IN',
  dietaryPreferences: ['NON_VEG', 'SPICY'],
  favoriteDishIds: ['dish-1', 'dish-4', 'dish-8', 'dish-16'],
};

export const SAMPLE_OUTLETS: OutletInfo[] = [
  {
    id: 'out-001',
    name: 'Chennai Central Flagship',
    code: 'CHN-01',
    address: '14, Khader Nawaz Khan Road, Nungambakkam',
    city: 'Chennai',
    phone: '+91 44 2833 4900',
    distanceKm: 1.8,
    isOpen: true,
    openingHours: '11:00 AM – 11:30 PM',
    availableTables: 14,
    totalTables: 28,
    deliveryAvailable: true,
    pickupAvailable: true,
    rating: 4.9,
    reviewCount: 1420,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    estimatedDeliveryMin: 25,
  },
  {
    id: 'out-002',
    name: 'Downtown Grand Bistro',
    code: 'DWT-02',
    address: '108, Anna Salai, Mount Road',
    city: 'Chennai',
    phone: '+91 44 2855 2100',
    distanceKm: 3.4,
    isOpen: true,
    openingHours: '11:30 AM – 11:00 PM',
    availableTables: 8,
    totalTables: 22,
    deliveryAvailable: true,
    pickupAvailable: true,
    rating: 4.8,
    reviewCount: 980,
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=600&q=80',
    estimatedDeliveryMin: 35,
  },
  {
    id: 'out-003',
    name: 'Cyber City Hub',
    code: 'CYB-03',
    address: 'Level 2, Phoenix MarketCity, Velachery',
    city: 'Chennai',
    phone: '+91 44 3008 3000',
    distanceKm: 6.2,
    isOpen: true,
    openingHours: '11:00 AM – Midnight',
    availableTables: 20,
    totalTables: 35,
    deliveryAvailable: true,
    pickupAvailable: true,
    rating: 4.7,
    reviewCount: 2150,
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
    estimatedDeliveryMin: 45,
  },
];

export const SAMPLE_CATEGORIES: FoodCategory[] = [
  { id: 'all', name: 'All Dishes', slug: 'all', iconName: 'Utensils', itemCount: 32, isPopular: true },
  { id: 'biryani', name: 'Biryani & Rice', slug: 'biryani', iconName: 'Flame', itemCount: 6, isPopular: true },
  { id: 'starters', name: 'Tandoor & Starters', slug: 'starters', iconName: 'Sparkles', itemCount: 7, isPopular: true },
  { id: 'pizzas', name: 'Gourmet Pizzas', slug: 'pizzas', iconName: 'Pizza', itemCount: 5, isPopular: true },
  { id: 'mains', name: 'North Indian Curries', slug: 'mains', iconName: 'Soup', itemCount: 6, isPopular: true },
  { id: 'south', name: 'South Indian Classics', slug: 'south', iconName: 'Coffee', itemCount: 4, isPopular: false },
  { id: 'asian', name: 'Asian Wok & Noodles', slug: 'asian', iconName: 'CookingPot', itemCount: 4, isPopular: false },
  { id: 'desserts', name: 'Artisanal Desserts', slug: 'desserts', iconName: 'Cake', itemCount: 4, isPopular: true },
  { id: 'beverages', name: 'Mocktails & Drinks', slug: 'beverages', iconName: 'GlassWater', itemCount: 5, isPopular: false },
  { id: 'combos', name: 'Chef Combos & Thalis', slug: 'combos', iconName: 'Crown', itemCount: 3, isPopular: true },
];

export const SAMPLE_COUPONS: Coupon[] = [
  {
    code: 'FEAST20',
    title: '20% OFF ON ORDERS OVER ₹500',
    description: 'Get 20% discount up to ₹150 on your entire gourmet meal.',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderAmount: 500,
    maxDiscountAmount: 150,
    validUntil: '30 Sep 2026',
    terms: ['Valid on all dine-in, takeaway, and delivery orders', 'Cannot be clubbed with other promos'],
  },
  {
    code: 'WELCOME100',
    title: 'FLAT ₹100 OFF',
    description: 'Flat ₹100 discount on your first online or table reservation order.',
    discountType: 'FLAT',
    discountValue: 100,
    minOrderAmount: 399,
    validUntil: '31 Dec 2026',
    terms: ['Applicable once per customer profile', 'Minimum order value ₹399'],
  },
  {
    code: 'WEEKEND50',
    title: 'WEEKEND SPECIAL ₹50 OFF',
    description: 'Enjoy ₹50 off on our chef signature combos and family biryanis.',
    discountType: 'FLAT',
    discountValue: 50,
    minOrderAmount: 450,
    validUntil: 'Every Fri-Sun',
    terms: ['Valid on weekends only'],
  },
  {
    code: 'ROYALTY25',
    title: '25% ROYAL DINE-IN SAVINGS',
    description: 'Exclusive 25% discount for dine-in guests booking tables on weekday evenings.',
    discountType: 'PERCENTAGE',
    discountValue: 25,
    minOrderAmount: 800,
    maxDiscountAmount: 300,
    validUntil: '31 Oct 2026',
    terms: ['Dine-in orders only', 'Valid Monday through Thursday'],
  },
];

export const SAMPLE_MENU_ITEMS: FoodItem[] = [
  // Biryani & Rice
  {
    id: 'dish-1',
    name: 'Hyderabadi Dum Chicken Biryani',
    description: 'Slow-cooked aromatic aged basmati rice layered with tender saffron-infused chicken, whole spices, and caramelized shallots. Served with spicy mirchi ka salan and cooling cucumber raita.',
    categoryId: 'biryani',
    categoryName: 'Biryani & Rice',
    cuisine: 'Mughlai',
    price: 349,
    originalPrice: 399,
    discountPercent: 13,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 2,
    isBestseller: true,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 1840,
    prepTimeMinutes: 20,
    calories: 680,
    allergens: ['Dairy'],
    ingredients: ['Basmati Rice', 'Chicken', 'Saffron', 'Ghee', 'Cardamom', 'Yogurt', 'Caramelized Onions'],
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'v-1', name: 'Regular (Serves 1)', price: 349, originalPrice: 399, isDefault: true },
      { id: 'v-2', name: 'Family Pot (Serves 2-3)', price: 699, originalPrice: 799 },
      { id: 'v-3', name: 'Jumbo Royal Feast (Serves 4-5)', price: 1199, originalPrice: 1399 },
    ],
    modifierGroups: [
      {
        id: 'mg-biryani-extra',
        name: 'Add Delicacies & Sides',
        minSelection: 0,
        maxSelection: 3,
        isRequired: false,
        options: [
          { id: 'm-egg', name: 'Extra Boiled Egg (2 pcs)', priceDelta: 40 },
          { id: 'm-chicken-piece', name: 'Extra Tandoori Chicken Piece', priceDelta: 110 },
          { id: 'm-salan', name: 'Extra Mirchi Ka Salan Bowl', priceDelta: 35 },
          { id: 'm-gulab', name: 'Add Hot Gulab Jamun (2 pcs)', priceDelta: 65 },
        ],
      },
      {
        id: 'mg-biryani-spice',
        name: 'Select Spice Intensity',
        minSelection: 1,
        maxSelection: 1,
        isRequired: true,
        options: [
          { id: 'sp-mild', name: 'Mild & Aromatic', priceDelta: 0 },
          { id: 'sp-med', name: 'Authentic Traditional (Medium)', priceDelta: 0, isDefault: true },
          { id: 'sp-hot', name: 'Extra Spicy Andhra Style', priceDelta: 0 },
        ],
      },
    ],
    tags: ['Bestseller', 'Chef Special', 'Halal', 'Signature'],
  },
  {
    id: 'dish-2',
    name: 'Awadhi Shahi Mutton Dum Biryani',
    description: 'Succulent prime cuts of goat meat marinated overnight in royal Awadhi spices, sealed in clay handi with long-grain basmati and rose water.',
    categoryId: 'biryani',
    categoryName: 'Biryani & Rice',
    cuisine: 'Awadhi',
    price: 469,
    originalPrice: 529,
    discountPercent: 11,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 2,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1120,
    prepTimeMinutes: 25,
    calories: 790,
    allergens: ['Dairy'],
    ingredients: ['Tender Goat Meat', 'Basmati Rice', 'Kewra Water', 'Pure Ghee', 'Cinnamon', 'Cloves'],
    imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'v-m1', name: 'Portion (Serves 1)', price: 469, originalPrice: 529, isDefault: true },
      { id: 'v-m2', name: 'Royal Handi (Serves 2-3)', price: 899, originalPrice: 999 },
    ],
    modifierGroups: [
      {
        id: 'mg-mutton-extras',
        name: 'Accompaniments',
        minSelection: 0,
        maxSelection: 2,
        isRequired: false,
        options: [
          { id: 'm-m-salan', name: 'Extra Shahi Gravy', priceDelta: 50 },
          { id: 'm-m-raita', name: 'Burani Garlic Raita', priceDelta: 45 },
        ],
      },
    ],
    tags: ['Royal', 'Bestseller'],
  },
  {
    id: 'dish-3',
    name: 'Nawabi Paneer Tikka Biryani',
    description: 'Charcoal-smoked cottage cheese cubes tossed in spicy tandoori marinade, layered with fragrant saffron rice, cashews, and mint.',
    categoryId: 'biryani',
    categoryName: 'Biryani & Rice',
    cuisine: 'North Indian',
    price: 299,
    originalPrice: 349,
    discountPercent: 14,
    isVeg: true,
    spiceLevel: 1,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 760,
    prepTimeMinutes: 18,
    calories: 590,
    allergens: ['Dairy', 'Nuts'],
    ingredients: ['Fresh Paneer', 'Basmati Rice', 'Cashews', 'Mint', 'Kashmiri Chili', 'Ghee'],
    imageUrl: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'v-p1', name: 'Single (Serves 1)', price: 299, isDefault: true },
      { id: 'v-p2', name: 'Sharing (Serves 2)', price: 549 },
    ],
    tags: ['Vegetarian', 'Popular'],
  },

  // Tandoor & Starters
  {
    id: 'dish-4',
    name: 'Tandoori Murgh Angara',
    description: 'Spring chicken steeped in mustard oil, roasted fenugreek, and crushed degi mirch, char-grilled to smoky tenderness in our traditional clay tandoor.',
    categoryId: 'starters',
    categoryName: 'Tandoor & Starters',
    cuisine: 'Tandoori',
    price: 329,
    originalPrice: 389,
    discountPercent: 15,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 3,
    isBestseller: true,
    isChefSpecial: true,
    rating: 4.8,
    reviewCount: 1350,
    prepTimeMinutes: 20,
    calories: 450,
    allergens: ['Dairy'],
    ingredients: ['Fresh Chicken', 'Mustard Oil', 'Kasuri Methi', 'Ginger Garlic', 'Lemon'],
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'v-t1', name: 'Half (4 Pcs)', price: 329, isDefault: true },
      { id: 'v-t2', name: 'Full Platter (8 Pcs)', price: 589, originalPrice: 659 },
    ],
    modifierGroups: [
      {
        id: 'mg-dip',
        name: 'Choice of Dip',
        minSelection: 0,
        maxSelection: 2,
        isRequired: false,
        options: [
          { id: 'dip-mint', name: 'Spicy Mint Chutney', priceDelta: 20 },
          { id: 'dip-garlic', name: 'Roasted Garlic Mayo', priceDelta: 25 },
        ],
      },
    ],
    tags: ['Smoky', 'Spicy', 'Tandoor'],
  },
  {
    id: 'dish-5',
    name: 'Bhatia Paneer Tikka Multani',
    description: 'Jumbo malai paneer cubes stuffed with herb mint paste, marinated in rich hung yogurt with carom seeds, and fire-roasted on skewers.',
    categoryId: 'starters',
    categoryName: 'Tandoor & Starters',
    cuisine: 'North Indian',
    price: 279,
    originalPrice: 320,
    discountPercent: 12,
    isVeg: true,
    spiceLevel: 1,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 920,
    prepTimeMinutes: 15,
    calories: 410,
    allergens: ['Dairy'],
    ingredients: ['Malai Paneer', 'Hung Curd', 'Ajwain', 'Bell Peppers', 'Onions'],
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Vegetarian', 'Clay Tandoor'],
  },
  {
    id: 'dish-6',
    name: 'Crispy Butter Garlic Prawns',
    description: 'Tiger prawns pan-seared with golden toasted garlic flakes, freshly crushed black pepper, bird’s eye chili, and a velvety lime-butter glaze.',
    categoryId: 'starters',
    categoryName: 'Tandoor & Starters',
    cuisine: 'Continental Fusion',
    price: 449,
    originalPrice: 499,
    discountPercent: 10,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 2,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 640,
    prepTimeMinutes: 15,
    calories: 380,
    allergens: ['Shellfish', 'Dairy'],
    ingredients: ['Tiger Prawns', 'Butter', 'Garlic', 'Parsley', 'Lime Juice'],
    imageUrl: 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Seafood', 'Chef Special'],
  },
  {
    id: 'dish-7',
    name: 'Dahi Ke Sholay',
    description: 'Crisp golden bread roll envelopes bursting with spiced hung curd, bell peppers, fresh coriander, and roasted cumin seeds.',
    categoryId: 'starters',
    categoryName: 'Tandoor & Starters',
    cuisine: 'Delhi Street Deluxe',
    price: 229,
    isVeg: true,
    spiceLevel: 1,
    rating: 4.6,
    reviewCount: 410,
    prepTimeMinutes: 12,
    calories: 320,
    allergens: ['Gluten', 'Dairy'],
    ingredients: ['Hung Curd', 'Bread', 'Green Chilies', 'Coriander'],
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Crispy', 'Vegetarian'],
  },

  // Gourmet Pizzas & Italian
  {
    id: 'dish-8',
    name: 'Truffle Burrata & Wild Mushroom Pizza',
    description: 'Hand-stretched Neapolitan sourdough crust baked in a wood-fired hearth. Topped with San Marzano tomato sauce, sautéed wild porcini mushrooms, creamy fresh burrata, and white truffle oil drizzle.',
    categoryId: 'pizzas',
    categoryName: 'Gourmet Pizzas',
    cuisine: 'Italian Artisan',
    price: 499,
    originalPrice: 569,
    discountPercent: 12,
    isVeg: true,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 880,
    prepTimeMinutes: 20,
    calories: 780,
    allergens: ['Gluten', 'Dairy'],
    ingredients: ['Sourdough Flour', 'Burrata', 'Porcini Mushrooms', 'Truffle Oil', 'Basil'],
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'vp-10', name: 'Medium (10" Artisanal)', price: 499, isDefault: true },
      { id: 'vp-14', name: 'Large (14" Family Feast)', price: 749, originalPrice: 849 },
    ],
    modifierGroups: [
      {
        id: 'mg-crust',
        name: 'Select Crust Type',
        minSelection: 1,
        maxSelection: 1,
        isRequired: true,
        options: [
          { id: 'cr-neo', name: 'Classic Neapolitan Sourdough', priceDelta: 0, isDefault: true },
          { id: 'cr-thin', name: 'Ultra Thin & Crispy Crust', priceDelta: 30 },
          { id: 'cr-cheese', name: 'Four-Cheese Stuffed Crust', priceDelta: 80 },
        ],
      },
      {
        id: 'mg-pizza-toppings',
        name: 'Extra Toppings',
        minSelection: 0,
        maxSelection: 4,
        isRequired: false,
        options: [
          { id: 'top-cheese', name: 'Extra Melted Buffalo Mozzarella', priceDelta: 60 },
          { id: 'top-jalapeno', name: 'Fire-Roasted Jalapeños', priceDelta: 30 },
          { id: 'top-olives', name: 'Kalamata Black Olives', priceDelta: 40 },
          { id: 'top-parmesan', name: 'Aged Shaved Parmesan', priceDelta: 50 },
        ],
      },
    ],
    tags: ['Artisan', 'Wood Fired', 'Chef Special'],
  },
  {
    id: 'dish-9',
    name: 'Fiery Peri-Peri Chicken Pizza',
    description: 'Tangy smoked marinara, pulled peri-peri chicken breast, caramelized red onions, roasted red peppers, and melted Monterey Jack cheese.',
    categoryId: 'pizzas',
    categoryName: 'Gourmet Pizzas',
    cuisine: 'Italian Fusion',
    price: 449,
    originalPrice: 499,
    discountPercent: 10,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 2,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 1210,
    prepTimeMinutes: 18,
    calories: 840,
    allergens: ['Gluten', 'Dairy'],
    ingredients: ['Peri-Peri Chicken', 'Mozzarella', 'Red Onions', 'Bell Peppers', 'Oregano'],
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    variants: [
      { id: 'vp-c10', name: 'Medium (10")', price: 449, isDefault: true },
      { id: 'vp-c14', name: 'Large (14")', price: 699 },
    ],
    modifierGroups: [
      {
        id: 'mg-peri-crust',
        name: 'Crust Preference',
        minSelection: 1,
        maxSelection: 1,
        isRequired: true,
        options: [
          { id: 'pcr-classic', name: 'Stone Baked Classic', priceDelta: 0, isDefault: true },
          { id: 'pcr-cheese', name: 'Cheese Burst Crust', priceDelta: 75 },
        ],
      },
    ],
    tags: ['Spicy', 'Bestseller'],
  },
  {
    id: 'dish-10',
    name: 'Classic Margherita Basilico',
    description: 'San Marzano tomato coulis, fresh fior di latte mozzarella, fragrant sweet basil leaves, and cold-pressed extra virgin olive oil.',
    categoryId: 'pizzas',
    categoryName: 'Gourmet Pizzas',
    cuisine: 'Italian Classic',
    price: 349,
    originalPrice: 399,
    discountPercent: 12,
    isVeg: true,
    rating: 4.7,
    reviewCount: 950,
    prepTimeMinutes: 15,
    calories: 650,
    allergens: ['Gluten', 'Dairy'],
    ingredients: ['Tomato Sauce', 'Mozzarella', 'Fresh Basil', 'Olive Oil'],
    imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Classic', 'Vegetarian'],
  },

  // North Indian Curries & Breads
  {
    id: 'dish-11',
    name: 'Old Delhi Butter Chicken (Murgh Makhani)',
    description: 'Tender tandoor-roasted chicken simmered in a velvety reduction of vine-ripened tomatoes, cashew cream, and fragrant dried fenugreek leaves.',
    categoryId: 'mains',
    categoryName: 'North Indian Curries',
    cuisine: 'Punjabi',
    price: 369,
    originalPrice: 419,
    discountPercent: 12,
    isVeg: false,
    isBestseller: true,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 2240,
    prepTimeMinutes: 18,
    calories: 620,
    allergens: ['Dairy', 'Nuts'],
    ingredients: ['Chicken Tikka', 'Tomato Gravy', 'White Butter', 'Heavy Cream', 'Kasuri Methi'],
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    modifierGroups: [
      {
        id: 'mg-curry-breads',
        name: 'Pair with Fresh Tandoori Breads',
        minSelection: 0,
        maxSelection: 3,
        isRequired: false,
        options: [
          { id: 'b-butter-naan', name: 'Garlic Butter Naan (1 pc)', priceDelta: 60 },
          { id: 'b-cheese-naan', name: 'Chili Cheese Naan (1 pc)', priceDelta: 85 },
          { id: 'b-roti', name: 'Laccha Tandoori Paratha (1 pc)', priceDelta: 50 },
        ],
      },
    ],
    tags: ['Legendary', 'Bestseller', 'Creamy'],
  },
  {
    id: 'dish-12',
    name: 'Dal Makhani Bukhara',
    description: 'Whole black urad lentils and red kidney beans slow-simmered over gentle charcoal embers for 36 hours with churned butter and tomato puree.',
    categoryId: 'mains',
    categoryName: 'North Indian Curries',
    cuisine: 'Mughlai',
    price: 289,
    originalPrice: 329,
    discountPercent: 12,
    isVeg: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1680,
    prepTimeMinutes: 12,
    calories: 490,
    allergens: ['Dairy'],
    ingredients: ['Black Lentils', 'Butter', 'Cream', 'Ginger', 'Tomato Paste'],
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Slow Cooked', 'Vegetarian', 'Signature'],
  },
  {
    id: 'dish-13',
    name: 'Paneer Lababdar',
    description: 'Fresh cottage cheese cubes folded into a robust, coarsely ground onion-tomato masala enriched with crushed melon seeds and ginger juliennes.',
    categoryId: 'mains',
    categoryName: 'North Indian Curries',
    cuisine: 'North Indian',
    price: 319,
    isVeg: true,
    spiceLevel: 1,
    rating: 4.7,
    reviewCount: 890,
    prepTimeMinutes: 15,
    calories: 520,
    allergens: ['Dairy', 'Nuts'],
    ingredients: ['Paneer', 'Onions', 'Tomatoes', 'Melon Seeds', 'Cream'],
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Vegetarian', 'Rich'],
  },

  // South Indian Classics
  {
    id: 'dish-14',
    name: 'Chettinad Pepper Chicken Fry',
    description: 'Succulent chicken tossed with freshly pounded black peppercorns, roasted coconut slivers, curry leaves, and fragrant shallots.',
    categoryId: 'south',
    categoryName: 'South Indian Classics',
    cuisine: 'Chettinad',
    price: 339,
    originalPrice: 379,
    discountPercent: 10,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 3,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 940,
    prepTimeMinutes: 16,
    calories: 440,
    allergens: [],
    ingredients: ['Chicken', 'Black Pepper', 'Curry Leaves', 'Shallots', 'Coconut'],
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Chettinad', 'Spicy', 'Signature'],
  },
  {
    id: 'dish-15',
    name: 'Ghee Podi Crispy Roast Dosa',
    description: 'Crisp golden crepe smeared with stone-ground spicy gun-powder (podi) and melted aromatic cow ghee. Served with 3 traditional chutneys and sambar.',
    categoryId: 'south',
    categoryName: 'South Indian Classics',
    cuisine: 'South Indian',
    price: 189,
    isVeg: true,
    spiceLevel: 1,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 1320,
    prepTimeMinutes: 10,
    calories: 390,
    allergens: ['Dairy'],
    ingredients: ['Rice Batter', 'Pure Ghee', 'Spicy Podi', 'Coconut Chutney', 'Sambar'],
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Crispy', 'Breakfast/Dinner', 'Vegetarian'],
  },

  // Asian Wok & Noodles
  {
    id: 'dish-16',
    name: 'Chili Garlic Hakka Wok Noodles',
    description: 'Hand-pulled wheat noodles tossed on blazing wok with sliced shiitake mushrooms, bell peppers, crunchy beans, scallions, and spicy chili-garlic oil.',
    categoryId: 'asian',
    categoryName: 'Asian Wok & Noodles',
    cuisine: 'Pan-Asian',
    price: 269,
    originalPrice: 299,
    discountPercent: 10,
    isVeg: true,
    isSpicy: true,
    spiceLevel: 2,
    rating: 4.7,
    reviewCount: 830,
    prepTimeMinutes: 14,
    calories: 480,
    allergens: ['Gluten', 'Soy'],
    ingredients: ['Wheat Noodles', 'Garlic', 'Chili Paste', 'Shiitake', 'Scallions'],
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    modifierGroups: [
      {
        id: 'mg-noodles-protein',
        name: 'Add Protein',
        minSelection: 0,
        maxSelection: 1,
        isRequired: false,
        options: [
          { id: 'np-chicken', name: 'Shredded Wok Chicken', priceDelta: 70 },
          { id: 'np-prawns', name: 'Wok Sautéed Prawns', priceDelta: 110 },
          { id: 'np-egg', name: 'Scrambled Farm Egg', priceDelta: 35 },
        ],
      },
    ],
    tags: ['Wok Fresh', 'Spicy'],
  },
  {
    id: 'dish-17',
    name: 'Crispy Dragon Chicken',
    description: 'Crispy battered chicken ribbons glazed in honey-chili sauce, toasted cashews, and fiery Sichuan peppercorns.',
    categoryId: 'asian',
    categoryName: 'Asian Wok & Noodles',
    cuisine: 'Indo-Chinese',
    price: 319,
    isVeg: false,
    isSpicy: true,
    spiceLevel: 2,
    rating: 4.8,
    reviewCount: 710,
    prepTimeMinutes: 15,
    calories: 490,
    allergens: ['Soy', 'Nuts'],
    ingredients: ['Chicken Strips', 'Honey Chili Glaze', 'Cashews', 'Sichuan Pepper'],
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Crispy', 'Popular'],
  },

  // Artisanal Desserts
  {
    id: 'dish-18',
    name: 'Sizzling Belgian Dark Chocolate Brownie',
    description: 'Warm, gooey 70% dark chocolate fudge brownie served on a cast iron sizzler with Tahitian vanilla bean gelato and hot molten chocolate ganache.',
    categoryId: 'desserts',
    categoryName: 'Artisanal Desserts',
    cuisine: 'Dessert',
    price: 249,
    originalPrice: 289,
    discountPercent: 14,
    isVeg: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1560,
    prepTimeMinutes: 10,
    calories: 540,
    allergens: ['Gluten', 'Dairy', 'Nuts'],
    ingredients: ['Belgian Chocolate', 'Vanilla Gelato', 'Butter', 'Walnuts', 'Cream'],
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Decadent', 'Bestseller'],
  },
  {
    id: 'dish-19',
    name: 'Zafrani Kesar Pista Rasmalai',
    description: 'Delicate poached cottage cheese discs steeped in reduced saffron milk infused with green cardamom, slivered pistachios, and edible 24k silver leaf.',
    categoryId: 'desserts',
    categoryName: 'Artisanal Desserts',
    cuisine: 'Royal Indian',
    price: 189,
    isVeg: true,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 840,
    prepTimeMinutes: 5,
    calories: 320,
    allergens: ['Dairy', 'Nuts'],
    ingredients: ['Chenna', 'Whole Milk', 'Kashmiri Kesar', 'Pistachios', 'Cardamom'],
    imageUrl: 'https://images.unsplash.com/photo-1627834377411-8da5f4f09de8?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Royal', 'Traditional'],
  },

  // Mocktails & Beverages
  {
    id: 'dish-20',
    name: 'Smoked Berry Rosemary Fizz',
    description: 'Wild blueberry puree, fresh rosemary sprigs, and lemon zest topped with sparkling soda and garnished with a smoking rosemary plume.',
    categoryId: 'beverages',
    categoryName: 'Mocktails & Drinks',
    cuisine: 'Mixology',
    price: 169,
    originalPrice: 199,
    discountPercent: 15,
    isVeg: true,
    isChefSpecial: true,
    rating: 4.8,
    reviewCount: 520,
    prepTimeMinutes: 6,
    calories: 120,
    allergens: [],
    ingredients: ['Wild Berries', 'Rosemary', 'Lime', 'Sparkling Water', 'Mint'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Refreshing', 'Artisanal'],
  },
  {
    id: 'dish-21',
    name: 'Kolkata Mango Lassi Shake',
    description: 'Alphonso mango pulp blended with rich hung curd, fresh cardamom, and toasted pistachio flakes.',
    categoryId: 'beverages',
    categoryName: 'Mocktails & Drinks',
    cuisine: 'Traditional Indian',
    price: 149,
    isVeg: true,
    rating: 4.8,
    reviewCount: 910,
    prepTimeMinutes: 5,
    calories: 240,
    allergens: ['Dairy', 'Nuts'],
    ingredients: ['Alphonso Mango', 'Yogurt', 'Cardamom', 'Pistachios'],
    imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Cooling', 'Sweet'],
  },

  // Chef Combos & Thalis
  {
    id: 'dish-22',
    name: 'The Grand Royal Feast Combo (Serves 2)',
    description: 'Includes 1 Hyderabadi Dum Chicken Biryani, 1 Old Delhi Butter Chicken, 2 Garlic Butter Naans, 1 Tandoori Murgh (4 pcs), Mirchi Ka Salan, Raita, and 2 Sizzling Brownies.',
    categoryId: 'combos',
    categoryName: 'Chef Combos & Thalis',
    cuisine: 'North Indian Feast',
    price: 899,
    originalPrice: 1099,
    discountPercent: 18,
    isVeg: false,
    isBestseller: true,
    isChefSpecial: true,
    rating: 4.9,
    reviewCount: 2310,
    prepTimeMinutes: 25,
    calories: 1650,
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    ingredients: ['Complete Multi-Course Meal for Two'],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Value Pack', 'Feast', 'Bestseller'],
  },
  {
    id: 'dish-23',
    name: 'Maharaja Vegetarian Thali',
    description: 'Lavish spread featuring Paneer Lababdar, Dal Makhani Bukhara, Vegetable Pulao, 2 Butter Rotis, Gulab Jamun, Papad, and Cucumber Raita.',
    categoryId: 'combos',
    categoryName: 'Chef Combos & Thalis',
    cuisine: 'Royal Vegetarian',
    price: 499,
    originalPrice: 580,
    discountPercent: 14,
    isVeg: true,
    rating: 4.8,
    reviewCount: 1140,
    prepTimeMinutes: 18,
    calories: 950,
    allergens: ['Dairy', 'Gluten'],
    ingredients: ['Complete Vegetarian Feast Platter'],
    imageUrl: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    tags: ['Vegetarian', 'Thali'],
  },
];
